spring.application.name=demo
# MongoDB ????????????
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.database=ECommercePlatform

spring.datasource.url=jdbc:mysql://localhost:3307/ecommerce_admin?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ????? SQL ?????????
logging.level.org.springframework.data.mongodb.core=DEBUG
